export const WORD_BANK = [
  "the", "of", "and", "a", "to", "in", "is", "you", "that", "it",
  "he", "was", "for", "on", "are", "as", "with", "his", "they", "at",
  "be", "this", "have", "from", "or", "one", "had", "by", "word", "but",
  "not", "what", "all", "were", "we", "when", "your", "can", "said", "there",
  "use", "an", "each", "which", "she", "do", "how", "their", "if", "will",
  "up", "other", "about", "out", "many", "then", "them", "these", "so", "some",
  "her", "would", "make", "like", "him", "into", "time", "has", "look", "two",
  "more", "write", "go", "see", "number", "no", "way", "could", "people", "my",
  "than", "first", "water", "been", "call", "who", "oil", "its", "now", "find",
  "long", "down", "day", "did", "get", "come", "made", "may", "part", "over",
  "new", "sound", "take", "only", "little", "work", "know", "place", "year", "live",
  "me", "back", "give", "most", "very", "after", "thing", "our", "just", "name",
  "good", "sentence", "man", "think", "say", "great", "where", "help", "through", "much",
  "before", "line", "right", "too", "mean", "old", "any", "same", "tell", "boy",
  "follow", "came", "want", "show", "also", "around", "form", "three", "small", "set",
  "put", "end", "does", "another", "well", "large", "must", "big", "even", "such",
  "because", "turn", "here", "why", "ask", "went", "men", "read", "need", "land",
  "different", "home", "us", "move", "try", "kind", "hand", "picture", "again", "change",
  "off", "play", "spell", "air", "away", "animal", "house", "point", "page", "letter",
  "mother", "answer", "found", "study", "still", "learn", "should", "america", "world"
];

export const QUOTES = [
  "The old typewriter clicked softly beneath the lamp while steam curled from a chipped porcelain cup.",
  "A well brewed coffee and a blank page are the truest companions of any patient writer.",
  "Every ribbon of ink tells a story long before the first sentence finds its shape.",
  "She rolled a fresh sheet of paper into the carriage and listened to the quiet hum of the room.",
  "Practice each morning until the keys feel like an extension of your own steady hands.",
  "The scent of roasted beans drifted through the study as another chapter slowly came to life.",
  "Somewhere between the clatter of keys and the hiss of the kettle a story begins to breathe.",
  "He tapped the return lever twice and smiled at the crooked little sentence he had just written.",
  "Fingers dance across worn letters while the afternoon light warms the edges of old paper.",
  "A single cup of coffee can turn an empty page into the start of something worth reading.",
  "The bell rang at the end of the line, a small triumph after every careful row of words.",
  "Slow down, breathe, and let each word land the way ink settles into fibered paper.",
  "The desk was cluttered with notes, pencil shavings, and the quiet ambition of a new draft.",
  "Speed will come with patience, but rhythm comes only from typing the same words again and again.",
  "Outside the window the rain kept time with the steady clatter of the typewriter keys.",
  "An antique machine, a warm drink, and an unhurried afternoon make for excellent practice.",
  "The most stubborn sentence often becomes the one you remember typing the fastest.",
  "Ink stained fingers are proof of an honest afternoon spent chasing better words.",
  "The paper carriage slid gently to the left, ready for another line of careful thought.",
  "Good habits are built one keystroke at a time, much like a good cup of coffee is brewed slowly."
];
